server:
  port: 8088

jwt:
  #eneler_key
  secret: U2FsdGVkX1/BLytas9jfD1Q0jzOZFBE64Z2tUJvziPU=
  expiration: 3600000

spring:
  main:
    allow-circular-references: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_SCHEMA:eneler}
    username: ${DB_USERNAME:alex_roosevelt}
    password: ${DB_PASSWORD:postgres}